# Generated by Django 5.2.1 on 2025-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('TP2', 'TurkPlayTV'), ('TP3', 'TureckiiTV')], max_length=3)),
                ('url', models.URLField(unique=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
            ],
        ),
    ]
